---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: silly-demo
  namespace: postgres
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: longhorn
    size: 5Gi
  monitoring:
    enablePodMonitor: true