services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${WG_HOST} # The public hostname of your VPN server.
      # Optional:
      - PASSWORD=${PASSWORD} # When set, requires a password when logging in to the Web UI.
      - WG_PORT=${WG_PORT} # The public UDP port of your VPN server. WireGuard will always listen on 51820 inside the Docker container.
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS} # Clients IP address range.
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS} # DNS server clients will use.
      - WG_MTU=1420 # The MTU the clients will use. Server uses default WG MTU.
      # - WG_ALLOWED_IPS=192.168.1.0/24 # Allowed IPs clients will use.
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
    env_file:
      - .env
    image: weejewel/wg-easy:latest
    container_name: wg-easy
    volumes:
      - wireguard-data:/etc/wireguard
    ports:
      - "${WG_PORT}:51820/udp"
      - "${WG_TCP_PORT}:${WG_TCP_PORT}/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wg.entrypoints=https"
      - "traefik.http.routers.wg.rule=Host(`${WG_HOST}`)"
      - "traefik.http.routers.wg.tls=true"
      - "traefik.http.services.wg.loadbalancer.server.port=${WG_TCP_PORT}"
      - "traefik.http.routers.wg.tls.certresolver=cloudflare"
      - "traefik.docker.network=proxy"

volumes:
  wireguard-data:
