---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  cloudflare-token: tsfY_in-tOkvNhK9USM4QhLTkWkJwcvWg1Yg6Wbf # MUST be an API token, NOT a Global API key!!! https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens
