---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        app.kubernetes.io/name: jellyfin
    spec:
      nodeSelector:
        vpn: "true"
      containers:
      - image: jellyfin/jellyfin
        imagePullPolicy: Always
        name: jellyfin
        ports:
        - containerPort: 8096
          name: web
          protocol: TCP
        env:
        - name: TZ
          value: Asia/Vladivostok
        volumeMounts:
        - mountPath: "/movies"
          readOnly: false
          name: smb
          subPath: media/movies
        - mountPath: "/music"
          readOnly: false
          name: smb
          subPath: media/music
        - mountPath: "/series"
          readOnly: false
          name: smb
          subPath: media/series
        - mountPath: "/videos"
          readOnly: false
          name: smb
          subPath: media/videos
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-jellyfin-smb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellyfin 
spec:
  ports:
  - name: web-tcp
    port: 8096
    protocol: TCP
    targetPort: 8096
  - name: web-udp
    port: 8096
    protocol: UDP
    targetPort: 8096
  selector:
    app: jellyfin
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.161 # this is your DNS IP, NOT THE GUI!
  type: LoadBalancer