---
version: "3.9"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vscode
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - PASSWORD=$PASSWORD #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=$SUDO_PASSWORD #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=$PROXY_DOMAIN #optional
      - DEFAULT_WORKSPACE=$DEFAULT_WORKSPACE #optional
    volumes:
      - $VOLUME_1:/config
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vscode.entrypoints=https"
      - "traefik.http.routers.vscode.rule=Host(`$PROXY_DOMAIN`)"
      - "traefik.http.routers.vscode.tls=true"
      - "traefik.http.services.vscode.loadbalancer.server.port=8443"
      - "traefik.http.routers.vscode.tls.certresolver=cloudflare"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

networks:
  proxy:
    external: true