version: '3.6'

services:

  ollama-webui:
    build:
      context: .
      args:
        OLLAMA_API_BASE_URL: '/ollama/api'
      dockerfile: Dockerfile
    image: ollama-webui:latest
    container_name: ollama-webui
    # ports:
    #   - 3000:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://192.168.1.41:11434/api"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.entrypoints=https"
      - "traefik.http.routers.ollama.rule=Host(`ollama.devcraft.app`)"
      - "traefik.http.routers.ollama.tls=true"
      - "traefik.http.services.ollama.loadbalancer.server.port=8080"
      - "traefik.http.routers.ollama.tls.certresolver=cloudflare"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.ollama.middlewares=default-whitelist@file"

networks:
  proxy:
    external: true
