---
- name: Update APT package index
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install NGINX
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Ensure NGINX is running and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes