apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["192.168.3.62"],"port":80,"protocol":"TCP","serviceName":"traefik:traefik","allNodes":false},{"addresses":["192.168.3.62"],"port":443,"protocol":"TCP","serviceName":"traefik:traefik","allNodes":false},{"addresses":["192.168.3.62"],"port":51824,"protocol":"UDP","serviceName":"traefik:traefik","allNodes":false}]
    kube-vip.io/loadbalancerIPs: 192.168.3.150
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: traefik
    metallb.universe.tf/ip-allocated-from-pool: first-pool
  creationTimestamp: '2023-12-25T09:50:38Z'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-26.0.0
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"service.kubernetes.io/load-balancer-cleanup": {}
      manager: kube-vip-cloud-provider
      operation: Update
      subresource: status
      time: '2023-12-25T09:50:38Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:kube-vip.io/loadbalancerIPs: {}
      manager: kube-vip-cloud-provider
      operation: Update
      time: '2023-12-25T09:50:39Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:metallb.universe.tf/ip-allocated-from-pool: {}
        f:status:
          f:loadBalancer:
            f:ingress: {}
      manager: controller
      operation: Update
      subresource: status
      time: '2023-12-25T10:12:17Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:helm.sh/chart: {}
        f:spec:
          f:allocateLoadBalancerNodePorts: {}
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:loadBalancerIP: {}
          f:ports:
            .: {}
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: helm
      operation: Update
      time: '2023-12-25T10:12:17Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:field.cattle.io/publicEndpoints: {}
        f:spec:
          f:ports:
            k:{"port":51824,"protocol":"UDP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
      manager: rancher
      operation: Update
      time: '2023-12-26T22:22:33Z'
  name: traefik
  namespace: traefik
  resourceVersion: '1738999'
  uid: f87b2b82-b279-4a9e-8f30-3dcb0b8a60d9
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.3.42
  clusterIPs:
    - 10.43.3.42
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 192.168.3.62
  ports:
    - name: web
      nodePort: 30316
      port: 80
      protocol: TCP
      targetPort: web
    - name: websecure
      nodePort: 30463
      port: 443
      protocol: TCP
      targetPort: websecure
    - name: wireguard
      nodePort: 30066
      port: 51824
      protocol: UDP
      targetPort: wireguard
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.168.3.62
