globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"
  - '--entrypoints.wireguard.address=:51824/udp'

deployment:
  enabled: true
  replicas: 2 # match with number of workers
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

nodeSelector: 
  worker: "true" # add these labels to your worker nodes before running - see video

ports:
  web:
    redirectTo:
      port: websecure
      priority: 10
  websecure:
    tls:
      enabled: true
  wireguard:
    port: 51824
    # hostPort: 51824
    containerPort: 51824
    expose: true
    exposedPort: 51824
    # The port protocol (TCP/UDP)
    protocol: UDP
      
ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    loadBalancerIP: 192.168.3.62 # this should be an IP in the Kube-VIP range
  loadBalancerSourceRanges: []
  externalIPs: []
