---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wg-easy
    app.kubernetes.io/instance: wg-easy
    app.kubernetes.io/name: wg-easy
  name: wg-easy
  namespace: wg-easy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wg-easy
  template:
    metadata:
      labels:
        app: wg-easy
        app.kubernetes.io/name: wg-easy
    spec:
      nodeSelector:
        worker: "true"
      containers:
        - env:
            - name: WG_HOST
              value: "37.8.154.67" # change me
            - name: PASSWORD
              value: "password"
            - name: WG_DEFAULT_DNS
              value: "192.168.3.68, wg-easy.svc.cluster.local"
          image: weejewel/wg-easy
          imagePullPolicy: Always
          name: wg-easy
          ports:
            - containerPort: 51820
              protocol: UDP
            - containerPort: 51821
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          volumeMounts:
            - mountPath: /etc/wireguard
              name: wg-easy
      restartPolicy: Always
      volumes:
        - name: wg-easy
          persistentVolumeClaim:
            claimName: wg-easy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy
  namespace: wg-easy
  labels:
    app: wg-easy
    app.kubernetes.io/instance: wg-easy
    app.kubernetes.io/name: wg-easy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wg-easy
  name: wg-easy-udp
  namespace: wg-easy
spec:
  ports:
  - name: wg-easy-udp
    port: 51824
    protocol: UDP
    targetPort: 51820
  selector:
    app: wg-easy
  type: ClusterIP
  # type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wg-easy
  name: wg-easy-web
  namespace: wg-easy
spec:
  ports:
  - name: wg-easy-web
    port: 51821
    protocol: TCP
    targetPort: 51821
  selector:
    app: wg-easy
  type: ClusterIP
