apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
  namespace: homepage
spec:
  containers:
  - name: temp-container
    image: busybox
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: temp-volume
      mountPath: "/app/public/icons"
  volumes:
  - name: temp-volume
    persistentVolumeClaim:
      claimName: homepage
  restartPolicy: Never
